name:                advent
version:             0.1.0.0
github:              "velveteer/aoc2018"
license:             BSD3
author:              "Josh Miller"
maintainer:          "notjoshmiller@gmail.com"

extra-source-files:
- README.md

default-extensions:
  - OverloadedStrings

description: Solutions to puzzles from adventofcode.com

ghc-options:
  -Wall
  -Werror

dependencies:
- attoparsec
- base >= 4.7 && < 5
- bytestring
- containers
- linear
- safe
- split
- text
- time
- time-locale-compat
- unordered-containers

library:
  source-dirs: src

executable:
  main: Main.hs
  ghc-options:
    -O3
    -threaded
  source-dirs: app
  dependencies:
    - advent

